services: 
  service-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"  # <-- Espaço depois do hífen e aspas duplas ou simples corretas
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=connect

  service-redis:
    image: bitnami/redis
    ports:
      - "6379:6379"  # <-- Mesma correção aqui
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
